### ISSUE TITLE
Multicast packet sending in Cooja doesn't work

### ISSUE THREAD

**Issue by Frank-en-stein** [nikirill/tinygroupdtls#1]

**Comment by nikirill** [comment]
It is not possible to use the library in Cooja in Contiki 2.7 because there is no simulation support for hardware with enough memory to deploy the library.

**Comment by sam-mh** [comment]
Can i modify any file in tinygroupdtls to work with cooja ? if that possible help me please, cause i need it in my master project .

**Comment by nikirill** [comment]
@sam-mh unfortunately, cooja does not have support for hardware with sufficient memory for this library. You have two options, either run this library on real hardware or create a new type of a device for cooja.

**Comment by sam-mh** [comment]
thank you D.nikirkill
i just wanna to ask you for the second part of the email " create a new
type of a device for cooja " if you have some tutorial or web site helping
to achieve that, i search on the internet but i can't find way to do that
thank you.
